# Generated by Django 2.2 on 2019-05-12 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='supKind',
        ),
        migrations.AddField(
            model_name='orders',
            name='deliveryMethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.DeliveryMethod'),
        ),
    ]
