# Generated by Django 2.2 on 2019-05-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_suppliers_deliverymethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='instock',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
