# Generated by Django 2.2 on 2019-05-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190512_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='arriveDate',
        ),
        migrations.AddField(
            model_name='orders',
            name='arriveDate',
            field=models.DateTimeField(null=True),
        ),
    ]
