# Generated by Django 2.2 on 2019-05-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190512_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
