# Generated by Django 2.2 on 2019-05-12 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190512_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='amount',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
