# Generated by Django 2.2 on 2019-05-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190512_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='arriveDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
