# Generated by Django 2.2 on 2019-05-12 04:10

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190512_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='arriveDate',
            field=models.DateField(default=shop.models.arrivedate),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipDate',
            field=models.DateField(default=shop.models.default_time),
        ),
    ]
