# Generated by Django 2.2 on 2019-05-12 04:14

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190512_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='arriveDate',
            field=models.DateField(default=shop.models.arrivedate, null=True),
        ),
    ]
