# Generated by Django 2.2 on 2019-05-12 04:16

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190512_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='arriveDate',
            field=models.DateTimeField(default=shop.models.arrivedate, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipDate',
            field=models.DateTimeField(default=shop.models.default_time),
        ),
    ]
