# Generated by Django 2.2 on 2019-05-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20190512_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='isOrder',
            field=models.BooleanField(default=False),
        ),
    ]
