# Generated by Django 2.2 on 2019-05-12 15:16

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orders_supid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='arriveDate',
            field=models.DateTimeField(default=shop.models.arrivedate),
        ),
    ]
